#!/bin/bash

#!/bin/bash

read -p "Proceed with ENux Finalizer [Y/n] " check

if [[ "$check" =~ ^[Nn]$ ]]; then
    echo "Finalizer aborted."
    sleep 2
    exit 0
fi

echo "---------------------------"
echo " WELCOME TO ENUX FINALIZER"
echo "---------------------------"
sleep 2
echo "Now sit back and relax as ENux Finalizer does everything"
sleep 3

# Fetch all supported distributions
brl fetch alpine --mirror https://dl-cdn.alpinelinux.org/alpine/ || true
brl fetch void --mirror https://repo-default.voidlinux.org || true
brl fetch arch --mirror https://fastly.mirror.pkgbuild.com/ || true
brl fetch centos || true
brl fetch gentoo --mirror https://gentoo.osuosl.org/ || true
brl fetch opensuse || true
echo "Note: Installing Nix"
sleep 1
echo "Nix is installed as an external toolchain, not a Bedrock stratum, therefore it will be managed independently from brl/pmm"
sleep 1
sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon

# Cleanup
rm -f ~/Desktop/enux-finaliser.desktop
rm -f /usr/local/bin/enux-finalizer
exit 0

echo "----------------------------------------------------"
echo "ENUX HAS BEEN SUCCESSFULLY INSTALLED ON YOUR COMPUTER"
echo "----------------------------------------------------"
sleep 4
exit 0
