#!/bin/sh

echo "[*] Copying read-only files to host using su"

su -c "mkdir -p /etc/fastfetch && cp etc/fastfetch/E-logo.txt /etc/fastfetch/E-logo.txt cp etc/fastfetch/config.jsonc /etc/fastfetch/config.jsonc && cp etc/nanorc /etc/nanorc"

su -c 'cat > /usr/bin/enuxfetch << EOF
#!/bin/sh
exec fastfetch
EOF
chmod +x /usr/bin/enuxfetch'

echo "[*] Done"
sleep 0.45
exit 0
